### ISSUE TITLE
Missing padding on tables when they have large texts

### ISSUE THREAD

**Issue by peluprvi** [vuetifyjs/vuetifyjs.com#31]
![image](https://user-images.githubusercontent.com/1561360/33399753-de011e86-d53a-11e7-895a-0fa149e8fa54.png)

![image](https://user-images.githubusercontent.com/1561360/33401208-a6c96b6c-d53f-11e7-88be-9c142632ec2b.png)

**Comment by johnleider** [comment]
Not a bug.

**Comment by KaelWD** [comment]
It does look shitty though. Even like 4px would help imo. 

```css
.table tbody td {
  padding: 4px 24px;
  font-weight: 400;
  font-size: 13px;
  line-height: 18px;
}
```
